name: isisdeps
channels:
  - anaconda
  - mgckind
  - jlaura
  - defaults
  - conda-forge
  - krodriguez
  - usgs-astrogeology
dependencies:
  - geotiff=1.4.1=0
  - libgcc=4.8.5=1
  - proj4=4.9.2=0
  - blas=1.1=openblas
  - boost=1.65.1=py27_0
  - boost-cpp=1.65.1=1
  - bzip2=1.0.6=1
  - cairo=1.14.6=4
  - cmake=3.9.1=0
  - cspice=66=0
  - curl=7.55.1=0
  - doxygen=1.8.14=0
  - eigen=3.3.3=0
  - expat=2.2.5=0
  - ffmpeg=3.2.4=3
  - flann=1.8.4=0
  - fontconfig=2.12.1=4
  - freetype=2.7=1
  - geos=3.5.1=1
  - gettext=0.19.8.1=0
  - giflib=5.1.4=0
  - glib=2.51.4=0
  - harfbuzz=1.3.4=2
  - hdf5=1.8.18=2
  - icu=58.2=0
  - jasper=1.900.1=4
  - jpeg=9b=2
  - krb5=1.14.2=0
  - lapack=3.6.1=1
  - libffi=3.2.1=3
  - libgfortran=3.0.0=0
  - libiconv=1.15=0
  - libpng=1.6.34=0
  - libssh2=1.8.0=2
  - libtiff=4.0.6=7
  - libuv=1.11.0=0
  - libwebp=0.5.2=7
  - libxcb=1.12=1
  - libxml2=2.9.7=0
  - m4=1.4.17=1
  - metis=5.1.0=3
  - mysql-connector-c=6.1.6=0
  - nanoflann=1.2.2=0
  - ncurses=5.9=10
  - ninja=1.7.2=0
  - nn=1.86.0=2
  - numpy=1.13.3=py27_blas_openblas_200
  - opencv=3.3.0=py27_blas_openblas_200
  - pcre=8.39=0
  - pip=9.0.1=py27_1
  - pixman=0.34.0=1
  - protobuf=3.2.0=py27_0
  - python=2.7.14=4
  - qwt=6.1.3=1
  - readline=7.0=0
  - rhash=1.3.4=0
  - setuptools=38.5.1=py27_0
  - six=1.11.0=py27_1
  - sqlite=3.20.1=2
  - suitesparse=4.5.4=blas_openblas_200
  - superlu=5.2.1=blas_openblas_201
  - tk=8.6.7
  - wheel=0.30.0
  - x264=20131217
  - xorg-kbproto=1.0.7
  - xorg-libx11=1.6.4
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xorg-xproto=7.0.31
  - xz=5.2.3=0
  - zlib=1.2.11=0
  - ca-certificates=2017.08.26
  - certifi=2018.1.18
  - gsl=2.2.1
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - mysql=5.7.20
  - openblas=0.2.19
  - openssl=1.0.2n
  - qt=5.6.2
  - bullet=2.86.1
  - ds9=7.5
  - embree=2.16.0
  - gmm=5.0
  - jama=125
  - naif=n0066
  - patchelf=0.9
  - pcl=1.8.1
  - qhull=7.2.0
  - tbb=4.4
  - tnt=126
  - vtk=7.1.1
  - xalan-c=1.11
  - xerces-c=3.1.4

